# Generated by Django 4.1.3 on 2022-11-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eta_um', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eta1',
            new_name='EtaUm',
        ),
    ]
