# Generated by Django 4.1.3 on 2022-11-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eta_um', '0003_etaum_lav_alter_etaum_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etaum',
            name='lav',
        ),
        migrations.AddField(
            model_name='etaum',
            name='lavagem',
            field=models.BooleanField(blank=True, default=False, verbose_name='Lavagem'),
        ),
    ]
