# Generated by Django 4.1.3 on 2022-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eta_um', '0004_remove_etaum_lav_etaum_lavagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etaum',
            name='cloro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cloro'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='cor_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cor Decantada'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='cor_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cor Tratada'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='filtro1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Filtro 1'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='filtro2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Filtro 2'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='filtro3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Filtro 3'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='filtro4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Filtro 4'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='ph_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ph Decantada'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='ph_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ph Tratada'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='turbidez_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Turbidez Decantada'),
        ),
        migrations.AlterField(
            model_name='etaum',
            name='turbidez_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Turbidez Tratada'),
        ),
    ]
