# Generated by Django 4.1.3 on 2022-11-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eta_um', '0005_alter_etaum_cloro_alter_etaum_cor_d_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etaum',
            options={'ordering': ('-data',), 'verbose_name': 'ETA 1', 'verbose_name_plural': 'ETAS 1'},
        ),
    ]
