# Generated by Django 4.1.3 on 2022-11-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captacao',
            name='cor_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cor Bruta'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='ph_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ph Bruta'),
        ),
        migrations.AlterField(
            model_name='captacao',
            name='turbidez_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Turbidez Bruta'),
        ),
    ]
