# Generated by Django 4.1.3 on 2022-11-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0002_alter_captacao_cor_b_alter_captacao_ph_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captacao',
            options={'ordering': ('-data',), 'verbose_name': 'CAPTAÇÃO', 'verbose_name_plural': 'CAPTAÇÕES'},
        ),
    ]
