# Generated by Django 4.1.3 on 2022-11-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etatres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.CharField(choices=[('0:00', '0:00'), ('2:00', '2:00'), ('4:00', '4:00'), ('6:00', '6:00'), ('8:00', '8:00'), ('10:00', '10:00'), ('12:00', '12:00'), ('14:00', '14:00'), ('16:00', '16:00'), ('18:00', '18:00'), ('20:00', '20:00'), ('22:00', '22:00')], max_length=5)),
                ('lavagem', models.BooleanField(blank=True, default=False, verbose_name='Lavagem')),
                ('cloro', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cloro')),
                ('cor_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cor Decantada')),
                ('ph_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ph Decantada')),
                ('turbidez_d', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Turbidez Decantada')),
                ('cor_t', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cor Tratada')),
                ('ph_t', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Ph Tratada')),
                ('turbidez_t', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Turbidez Tratada')),
            ],
            options={
                'verbose_name': 'ETA TRÊS',
            },
        ),
    ]
