# Generated by Django 4.1.3 on 2022-11-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eta_tres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etatres',
            options={'ordering': ('-data',), 'verbose_name': 'ETA TRÊS'},
        ),
    ]
